project:
  type: website

website:
  title: "ggsql"
  description: |
    The home of ggsql. A declarative visualisation language build on top of SQL
    and the grammar of graphics.
  site-url: https://ggsql.org
  repo-url: https://github.com/ggsql-dev/ggsql
  issue-url: https://github.com/ggsql-dev/ggsql/issues
  repo-branch: gh-pages
  image: assets/logo.png
  image-alt: |
    The ggsql logo showing a pencil tracing a lineplot with points. The pencil
    handle is made up of the classic database silo icon and is coloured in a
    gradient teal.
  announcement:
    icon: info-circle
    dismissable: true
    content: "ggsql is still in early development and all functionality is subject to change"
    type: primary
    position: below-navbar
  twitter-card:
    card-style: summary
  open-graph: true
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - installation.qmd
      - text: Syntax
        menu:
          - text: Overview
            href: syntax/index.qmd
          - text: "---"
          - text: "`VISUALISE`"
            href: syntax/clause/visualise.qmd
          - text: "`DRAW`"
            href: syntax/clause/draw.qmd
          - text: "`SCALE`"
            href: syntax/clause/scale.qmd
          - text: "`FACET`"
            href: syntax/clause/facet.qmd
          - text: "`PROJECT`"
            href: syntax/clause/project.qmd
          - text: "`LABEL`"
            href: syntax/clause/label.qmd
      - examples.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/ggsql-dev/ggsql
          - text: Report a Bug
            href: https://github.com/ggsql-dev/ggsql/issues
  sidebar:
    id: syntax
    title: Syntax
    style: "floating"
    search: true
    contents:
      - text: Overview
        href: syntax/index.qmd
      - section: "Main clauses"
        contents:
          - text: "`VISUALISE`"
            href: syntax/clause/visualise.qmd
          - text: "`DRAW`"
            href: syntax/clause/draw.qmd
          - text: "`SCALE`"
            href: syntax/clause/scale.qmd
          - text: "`FACET`"
            href: syntax/clause/facet.qmd
          - text: "`PROJECT`"
            href: syntax/clause/project.qmd
          - text: "`LABEL`"
            href: syntax/clause/label.qmd
      - section: Layers
        contents:
          - auto: syntax/layer/*


format:
  html:
    syntax-definitions:
      - ggsql.xml
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/gh/posit-dev/supported-by-posit/js/badge.min.js"
              data-light-bg="#94D2BD"
              data-dark-bg="#001219"></script>
