name: build-test.yaml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Increase disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install tree-sitter-cli
        run: npm install -g tree-sitter-cli

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Caching
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-build
          cache-on-failure: true

      - name: Build with cargo
        run: cargo build --verbose

      - name: Run tree-sitter tests
        working-directory: tree-sitter-ggsql
        run: tree-sitter test

      - name: Run Rust tests
        if: success()
        run: cargo test --lib --bins

      - name: Run Rust formatting check
        if: success()
        run: cargo fmt --all -- --check
