name: R-CMD-Check.yaml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  R-CMD-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Increase disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check disk space
        run: df -h

      - name: Setup CLI tools
        run: cargo install --path src

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          working-directory: ggsql-R

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ggsql-R
          extra-packages: any::rcmdcheck
          needs: check

      - name: Checking R package
        uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ggsql-R
